apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: vaishnavigi/catalyst
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

#service type

apiVersion: v1
kind: Service
metadata:
  name: catalyst-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
